[components.core]
name = "core"

[components.core.config]
brokers = ["127.0.0.1:9092"]

[components.core.config.storage]
name = "mysql"

[components.log]
name = "log"

[components.log.config.default]
out = "std"
level = "debug"
format = "text"